### ISSUE TITLE
[Backend] API Hook for Logging in a user

### ISSUE THREAD

**Issue by pbokey** [brewhaha-jd/brewhaha#4]
Similar to creating a user we need a hook to login a user.

The frontend will provide the email address and the password of the account.

The backend should return the user account stored in the database (first name, last name, email, username, etc.) or some kind of error message if the user was not found.

**Comment by nickhutch** [comment]
@pbokey should we instead do the username?

**Comment by prabogey** [comment]
I feel like email is easier since it’s less to remember for them. I’m fine with either way though.
